---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    job:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(job_id) - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO            
        formatter: simple
        filename: /tmp/agent.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

    job_file_handler:
        class: enstratius.agent.util.JobLogHandler
        level: INFO
        formatter: simple
        encoding: utf8
        filename_format: "/tmp/%(logname)s-%(job_id)s.log"

loggers:
    enstratius.agent:
        level: INFO
        handlers: [file_handler]
        propagate: no

    enstratius.agent.jobs:
        level: INFO
        handlers: [job_file_handler]
        propagate: no


root:
    level: INFO
    handlers: [file_handler]