---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s %(asctime)s [%(name)s] %(filename)s:%(lineno)d [(REQUEST=%(dcm_request_id)s)] %(message)s"
    todcm:
        format: "%(asctime)s [%(name)s] %(filename)s:%(lineno)d [(REQUEST=%(dcm_request_id)s)] %(message)s"
    wire:
        format: "[%(asctime)s] %(message)s"


filters:
    add_request:
        (): dcm.eventlog.tracer.RequestFilter


handlers:
    file_handler:
        class: dcm.agent.logger.DCMAgentLogger
        level: @LOG_LEVEL@
        formatter: simple
        filename: @LOGFILE_PATH@
        owner: @DCM_USER@
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
        filters: [add_request]

    wire_handler:
        class: dcm.agent.logger.DCMAgentLogger
        level: INFO
        formatter: wire
        filename: @LOGFILE_PATH@.wire
        owner: @DCM_USER@
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

    job_runner_file_handler:
        class: dcm.agent.logger.DCMAgentLogger
        level: @LOG_LEVEL@
        formatter: simple
        filename: @LOGFILE_PATH@.job_runner
        owner: @DCM_USER@
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
        filters: [add_request]

    dcm_logger:
        class: dcm.agent.logger.dcmLogger
        level: @LOG_LEVEL@
        formatter: todcm
        filters: [add_request]
        encoding: utf8


loggers:
    dcm.agent:
        level: @LOG_LEVEL@
        handlers: [file_handler]
        propagate: no

    dcm.agent.messaging:
        level: @LOG_LEVEL@
        handlers: [file_handler]
        propagate: no

    dcm.agent.job_runner:
        level: @LOG_LEVEL@
        handlers: [job_runner_file_handler]
        propagate: no

    dcm.agent.plugins:
        level: @LOG_LEVEL@
        handlers: [file_handler]
        propagate: no

    dcm.agent.log.to.agent.manager:
        level: @LOG_LEVEL@
        handlers: [dcm_logger, file_handler]
        propagate: no

    DCM_AGENT_WIRE:
        level: INFO
        handlers: [wire_handler]
        propagate: no
root:
    level: @LOG_LEVEL@
    handlers: [file_handler]
