---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s %(asctime)s [%(name)s] %(filename)s:%(lineno)d [(REQUEST=%(dcm_request_id)s)] %(message)s"
    todcm:
        format: "%(asctime)s [%(name)s] %(filename)s:%(lineno)d [(REQUEST=%(dcm_request_id)s)] %(message)s"


filters:
    add_request:
        (): dcm.eventlog.tracer.RequestFilter


handlers:
    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: @LOGFILE_PATH@
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
        filters: [add_request]

    dcm_logger:
        class: dcm.agent.logger.dcmLogger
        level: DEBUG
        formatter: todcm
        filters: [add_request]
        encoding: utf8


loggers:
    dcm.agent:
        level: DEBUG
        handlers: [file_handler]
        propagate: no

    dcm.agent.messaging:
        level: INFO
        handlers: [file_handler]
        propagate: no

    dcm.agent.job_runner:
        level: DEBUG
        handlers: [file_handler]
        propagate: no

    dcm.agent.jobs:
        level: DEBUG
        handlers: [file_handler]
        propagate: no

    dcm.agent.log.to.agent.manager:
        level: DEBUG
        handlers: [dcm_logger, file_handler]
        propagate: no


root:
    level: INFO
    handlers: [file_handler]
